SCMOD-8730: Added expiration policy
JobService/job-service-client pull request #4
Opened 2021-04-15 11:17 UTC by xbreizh

https://portal.digitalsafe.net/browse/SCMOD-8730

2021-04-15 11:25 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=JobService&REPO_NAME=job-service-client&BRANCH_NAME=SCMOD-8730) to go ahead and create the build...

2021-04-15 11:33 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/JobService/job/JobService~job-service-client~SCMOD-8730~CI

2021-04-26 12:41 UTC, dermot-hardy commented on job-service-contract/src/main/resources/com/hpe/caf/services/job/swagger.yaml
> +        format: date-time
Failure time changing feels like a breaking change.

2021-04-30 18:37 UTC, dermot-hardy requested changes
Cut this down to just the changes required to add expiration policy.  Do not try to align the contract with what is in Job Service (not for this PR anyway).

2021-05-04 08:19 UTC, xbreizh commented
> Cut this down to just the changes required to add expiration policy. Do not try to align the contract with what is in Job Service (not for this PR anyway).

Done

2021-05-04 13:21 UTC, dermot-hardy commented
Remove the unnecessary whitespace changes also.

2023-02-08 13:30 UTC, closed without merging